### ISSUE TITLE
BulkMessages example is not compiling on Travis with Platformio (Compiling fine in Arduino IDE)

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/Universal-Arduino-Telegram-Bot#19]
As per title

[Here is an example of a failed build](https://travis-ci.org/witnessmenow/Universal-Arduino-Telegram-Bot/jobs/190111729)

> /tmp/tmpfRZHsn/src/BulkMessages.ino: In function 'ArduinoJson::JsonObject& getSubscribedUsers(ArduinoJson::JsonBuffer&)':
> /tmp/tmpfRZHsn/src/BulkMessages.ino:113:36: error: 'class ArduinoJson::JsonBuffer' has no member named 'parseObject'
> JsonObject& users = jsonBuffer.parseObject(file_content);

I'm guessing the platformio config or Travis config needs to be tweaked

**Comment by rusboard** [comment]
I have same error, when updated yesterday ArduinoJson library to 3.8.0, I rolled back to 3.7.3 again.
Will try fix later for 3.8.0. I don't know what changed in library.

**Comment by witnessmenow** [comment]
The platformio is using the latest arduinojson library 5.8.0 but an earlier one can be specified if needed

**Comment by rusboard** [comment]
Oh, my mistake about v3. Yes, 5.8.0 not working with my example. But 5.7.3 working.
I will later find out, where is problem and what need to fix.

**Comment by witnessmenow** [comment]
Thanks! Let me know if you need anything

**Comment by witnessmenow** [comment]
Fixed by @rusboard in #21
